services:
  db: 
    image: postgres:15.7
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_userdb:/var/lib/postgresql/data
  

  db-testdb:  # test db for unit tests
    image: postgres:15.7
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_testdb:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/userdb
    ports:
      - "8000:8000"

volumes:
  postgres_data_userdb:
  postgres_data_testdb:
