apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "hw-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "hw-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "hw-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "hw-api.fullname" . }}
                  key: database-url
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector: 
        {{- toYaml .Values.nodeSelector | nindent 10 }}
