apiVersion: v1
kind: Service
metadata:
  name: {{ include "hw-api.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "hw-api.name" . }}
    release: {{ .Release.Name }}
